declare module '@editorjs/embed';
declare module '@editorjs/header';
declare module '@editorjs/list';
declare module '@editorjs/image';
declare module '@editorjs/quote';
declare module '@editorjs/marker';
declare module '@editorjs/inline-code';
declare module '@editorjs/link';
declare module '@editorjs/code';